<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_ico-newHeaderLogo</name>
   <tag></tag>
   <elementGuidId>487e4bc6-1623-4fcc-93ed-43e0699a3d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logo > i.ico-newHeaderLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='themeSnipe']/div/div/div[4]/div/a/i</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;https://www.yatra.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>efad8e32-6afe-4450-94b7-698863a95c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico-newHeaderLogo</value>
      <webElementGuid>90067584-c3c6-45c5-aba9-f95eb7a92c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;themeSnipe&quot;)/div[@class=&quot;yatra-header   headerGrp&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;header-container desktop-only&quot;]/div[@class=&quot;header-left-menu ftL&quot;]/a[@class=&quot;logo&quot;]/i[@class=&quot;ico-newHeaderLogo&quot;]</value>
      <webElementGuid>890c7967-0088-41ce-a5ca-4bbbb0497e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='themeSnipe']/div/div/div[4]/div/a/i</value>
      <webElementGuid>3c59f22c-81fb-4be7-874e-89836e47e2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>a8ab912a-9c21-4c51-9120-953740d7c110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
