<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hotels</name>
   <tag></tag>
   <elementGuidId>0c4bf3ac-37f4-426d-8d25-df55e2204c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#booking_engine_hotels > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='booking_engine_hotels']/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Hotels&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a1927ac-c119-4f9d-a0f7-811135f44508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels</value>
      <webElementGuid>dd607bc8-ece8-4df4-9227-5c6325d405f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;booking_engine_hotels&quot;)/span[1]</value>
      <webElementGuid>e6f95937-f044-433f-adf7-e5cefd52b15d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='booking_engine_hotels']/span</value>
      <webElementGuid>8af78a8c-fe18-4f27-8ebd-dcfd583ede55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[2]/following::span[2]</value>
      <webElementGuid>5d9f4935-936a-4f0b-85be-500b0e77ef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yatra for Business'])[2]/following::span[4]</value>
      <webElementGuid>d156d93f-247d-4c30-b779-20c44252f792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holidays'])[2]/preceding::span[2]</value>
      <webElementGuid>cea5b7e4-a8f9-48c8-bc6d-7bc5c06c17f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buses'])[2]/preceding::span[4]</value>
      <webElementGuid>a1b6a273-f093-407b-a928-e87514511c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>70557747-b751-4e34-b601-275b806a3832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hotels' or . = 'Hotels')]</value>
      <webElementGuid>5b6a1813-3f8e-4e55-97c0-ba2570caf8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
